### ISSUE TITLE
Featured Image Slider on interior pages

### ISSUE THREAD

**Issue by sameera2011** [kbauman/Capital-Sisters#16]
Can we standardize the size of this slider so that it is always the same as the one on the "Who We Serve" page? It currently expands/shrinks based on text input.

**Comment by sameera2011** [comment]
hey! just wanted to follow up to see if the minimum height has been implemented on this. in testing for mobile, i'm seeing some issues that i think will be resolved by this fix as well.
thanks!

**Comment by kbauman** [comment]
What issues are you seeing?

On Mon, Jan 12, 2015 at 11:42 AM, sameera2011 <notifications@github.com>
wrote:

> hey! just wanted to follow up to see if the minimum height has been
> implemented on this. in testing for mobile, i'm seeing some issues that i
> think will be resolved by this fix as well.
> thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kbauman/Capital-Sisters/issues/16#issuecomment-69621285>
> .
>



-- 
Kevin Bauman
248.935.4695
www.kevinbauman.com

**Comment by sameera2011** [comment]
well, on this page specifically http://csi.domotobrands.com/investing/social-dividend/
 it is cutting off the images, and then when it condenses/collapses for mobile, the text box remains really long due to the spaces we had to input to try to expand the size of the slider (i've since removed these hard returns). Kevin had mentioned creating a minimum height for these sliders so that they always match the height of the one on the Who We Serve page

**Comment by kbauman** [comment]
Added minimum height to interior sliders. If the content on a slide is taller than the minimum, the slide heights will be different per slide.
