### ISSUE TITLE
Newsletter - Connect to MailChimp

### ISSUE THREAD

**Issue by sameera2011** [kbauman/Capital-Sisters#23]
Jenny had provided mail chimp credentials. We need the "e-newsletter" link in the site header to link to the E-News Sign Up page, and that page needs the MailChimp email submission button on it.

**Comment by michaellaness** [comment]
I need you guys to login into mailchimp when you can and fill out the correct profile info, contact and such. 

I have the mailchimp plugin set up, will just need to connect on the live staging site bc it wouldn't allow me to do this locally.

**Comment by sameera2011** [comment]
Can we get this plugged in on the staging site? Kevin, this and the addition of the text field can be added to staging tomorrow morning. I'll be sure to get a list of updates from the client over to you tonight.

Thanks,
Sameera
