### ISSUE TITLE
finalizing map template 

### ISSUE THREAD

**Issue by sameera2011** [kbauman/Capital-Sisters#25]
can we add a little padding under the map so it doesn't crowd the text below? right now it's running into the content header

**Comment by michaellaness** [comment]
- [ ] Investor Relations -  increase map vertical padding
- [ ] Investor Relations - Add icons for 'documentation' module
- [ ] Global Footprint - Make accordion widget ul's 2 column

**Comment by kbauman** [comment]
Map pins were added awhile ago.

**Comment by sameera2011** [comment]
looks great!
