### ISSUE TITLE
Footer Links Collapsing in Mobile

### ISSUE THREAD

**Issue by sameera2011** [kbauman/Capital-Sisters#29]
Footer links: privacy policy/ legal terms/ etc... aren't collapsing evenly when they break down for mobile viewing. Specifically on FAQ. We're thinking that the backslashes are providing the other links with padding.

Can we try adding a backslash before privacy policy and one after FAQ to see if this resolves?
![screenshot_2015-01-07-15-22-05](https://cloud.githubusercontent.com/assets/10201361/5709586/550eb82e-9a58-11e4-81f6-ddc23540f61e.png)

**Comment by kbauman** [comment]
That's just the way they wrap. How do you want them to look? Each one could
be on a separate line at a certain break point, but I don't know that that
is a better solution. It's just like paragraph text wrapping. It wraps
where the words end, and based on the space available.

On Mon, Jan 12, 2015 at 12:41 PM, sameera2011 <notifications@github.com>
wrote:

> Footer links: privacy policy/ legal terms/ etc... aren't collapsing evenly
> when they break down for mobile viewing. Specifically on FAQ. We're
> thinking that the backslashes are providing the other links with padding.
>
> Can we try adding a backslash before privacy policy and one after FAQ to
> see if this resolves?
> [image: screenshot_2015-01-07-15-22-05]
> <https://cloud.githubusercontent.com/assets/10201361/5709586/550eb82e-9a58-11e4-81f6-ddc23540f61e.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kbauman/Capital-Sisters/issues/29>.
>



-- 
Kevin Bauman
248.935.4695
www.kevinbauman.com

**Comment by sameera2011** [comment]
Yeah, doing separate lines is not desirable here I agree. If adding a backslash doesn't resolve, then I'm not sure what the fix is. But have we tried giving that a whirl?

**Comment by kbauman** [comment]
What I'm wondering is what the desired outcome is, because just adding
space may fix it for one phone, but make it worse on another. Do we want a
set number of links per line?

I'm happy to add more slashes, but I want to make sure I'm actually
understand what we want to happen.

On Fri, Jan 16, 2015 at 11:13 AM, sameera2011 <notifications@github.com>
wrote:

> Yeah, doing separate lines is not desirable here I agree. If adding a
> backslash doesn't resolve, then I'm not sure what the fix is. But have we
> tried giving that a whirl?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kbauman/Capital-Sisters/issues/29#issuecomment-70296180>
> .
>



-- 
Kevin Bauman
248.935.4695
www.kevinbauman.com

**Comment by kbauman** [comment]
Here is what it would look like with the extra "/" before and after.
![footer-nav](https://cloud.githubusercontent.com/assets/78949/5782075/95184474-9d75-11e4-940b-4a8d19c6a840.png)

**Comment by sameera2011** [comment]
I think this seem sot fix the issue. There was a padding issue with the wrap in that the FAQ without the slashes was nudged right up under the line above. The slashes now make everything wrap more uniformly in height. If you have a solution instead of the slashes that you think will accomplish this, I'm sure that's fine too!
Thanks, Kevin.

**Comment by kbauman** [comment]
I thought the general layout was the issue. The issue for the faq is simply
the height of the element, so it can be fixed with or without the /. If you
like it better with, I do that. Otherwise it's an adjustment to the line
height.

Kevin

**Comment by sameera2011** [comment]
Oh, yes, if we can accomplish it without having to include the slashes, let's do that, please.

Thank you!
