### ISSUE TITLE
Landing Page Buttons- Mobile

### ISSUE THREAD

**Issue by sameera2011** [kbauman/Capital-Sisters#30]
The spacing and returns in the structuring of the buttons on the landing pages (Impact, Investing, Advocacy etc). Are causing the buttons that navigate to the lower level pages to not space out correctly. Is there a way to change the letting and make them space more properly.
![screenshot_2015-01-07-15-22-34](https://cloud.githubusercontent.com/assets/10201361/5709727/74d79e72-9a59-11e4-879d-36948943bcab.png)
![screenshot_2015-01-07-15-47-28](https://cloud.githubusercontent.com/assets/10201361/5709728/74dbb0b6-9a59-11e4-8774-9209ed692cdb.png)

**Comment by kbauman** [comment]
This is because there are two <br> tags and a '&nbsp; between 'policy' and
'education'.



On Mon, Jan 12, 2015 at 12:49 PM, sameera2011 <notifications@github.com>
wrote:

> The spacing and returns in the structuring of the buttons on the landing
> pages (Impact, Investing, Advocacy etc). Are causing the buttons that
> navigate to the lower level pages to not space out correctly. Is there a
> way to change the letting and make them space more properly.
> [image: screenshot_2015-01-07-15-22-34]
> <https://cloud.githubusercontent.com/assets/10201361/5709727/74d79e72-9a59-11e4-879d-36948943bcab.png>
> [image: screenshot_2015-01-07-15-47-28]
> <https://cloud.githubusercontent.com/assets/10201361/5709728/74dbb0b6-9a59-11e4-8774-9209ed692cdb.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kbauman/Capital-Sisters/issues/30>.
>



-- 
Kevin Bauman
248.935.4695
www.kevinbauman.com

**Comment by kbauman** [comment]
The same is true for the advocacy page as well.

**Comment by kbauman** [comment]
Added bottom margin to buttons. Please remove br tags and &npsp; entities.
