### ISSUE TITLE
Heading Styles to Mimic Block Text Quotes

### ISSUE THREAD

**Issue by sameera2011** [kbauman/Capital-Sisters#31]
Having block text quotes in the body of some pages is causing formatting issues (see examples). Can we make one of the heading styles mimic the block text style so that we can control the alignment? Should be the same styling as the "Featured Text"
![screenshot_2015-01-07-15-46-47](https://cloud.githubusercontent.com/assets/10201361/5709798/f481adca-9a59-11e4-8ee3-8f3eee77ea25.png)
![screenshot_2015-01-07-15-50-12](https://cloud.githubusercontent.com/assets/10201361/5709799/f485b474-9a59-11e4-875a-178b3ca7f88a.png)
![screenshot_2015-01-07-15-50-58]

**Comment by michaellaness** [comment]
I put in a mobile query that fixes the issue you seem to be having on mobile.

The blockquote style should work the way blockquotes are meant to be used. If you are wanting to use headline styles like blockquotes, this won't work. They are all set up according to the mockups and WordPress best practices.
