### ISSUE TITLE
text styles/shortcodes

### ISSUE THREAD

**Issue by sameera2011** [kbauman/Capital-Sisters#33]
hey guys,

the bullet points still aren't working - see screen grab.

also, the block quote isn't accommodating longer words as is... would it be possible to increase the width there or make it so it just stretches the length of the text panel and can either be selected align left or align right to make it do so?
![screen shot 2015-01-27 at 12 33 14 pm](https://cloud.githubusercontent.com/assets/10201361/5925464/ec8fafd6-a620-11e4-86c9-8edf5dc56e66.png)

**Comment by kbauman** [comment]
I will take a look a the lists. Block quotes will potentially always have
this problem unless they are allowed to stretch across the screen. With a
set width, a word can always be too long.

On Tue, Jan 27, 2015 at 12:35 PM, sameera2011 <notifications@github.com>
wrote:

> hey guys,
>
> the bullet points still aren't working - see screen grab.
>
> also, the block quote isn't accommodating longer words as is... would it
> be possible to increase the width there or make it so it just stretches the
> length of the text panel and can either be selected align left or align
> right to make it do so?
> [image: screen shot 2015-01-27 at 12 33 14 pm]
> <https://cloud.githubusercontent.com/assets/10201361/5925464/ec8fafd6-a620-11e4-86c9-8edf5dc56e66.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kbauman/Capital-Sisters/issues/33>.
>



-- 
Kevin Bauman
248.935.4695
www.kevinbauman.com

**Comment by sameera2011** [comment]
Thanks Kevin.  For bullet points, they appear to be mostly fixed but have lost the indentation throughout bullet-pointed content. See the "invest" page under investing. Can we just make it so that all the content is aligned to the same indentation under a bullet point?

Re. block quotes; That makes sense. I'll get back to you if any further changes are required here.
