### ISSUE TITLE
widgets on Investor Relations page

### ISSUE THREAD

**Issue by sameera2011** [kbauman/Capital-Sisters#35]
Hey Kevin,

The widgets on the Investor Relations page are overlapping the pledge box. Can you please adjust?  Thanks!

**Comment by kbauman** [comment]
Any reason this is reopened?

**Comment by sameera2011** [comment]
looks great! except the widget now makes the testimonial box randomly go bold and then not. ugh, sorry!

Also, can we make the text under the documents (the legal jargon) font a bit less heavy? perhaps to the size of the text under the pledge button?
