### ISSUE TITLE
new pages - styling

### ISSUE THREAD

**Issue by sameera2011** [kbauman/Capital-Sisters#38]
Hey Kevin,

Can we make sure new pages are following the CSS of the rest of the site? for example, the "technical advisors" page under "our story" is using the default template, but the text appears a lot bolder/brighter than throughout the rest of the site. not sure why this would be...

**Comment by kbauman** [comment]
I'm sorry, but I don't see a difference. Looks exactly the same to me, and
when I inspect the text both FireFox and Chrome show the same CSS.

On Thu, Feb 12, 2015 at 12:13 PM, sameera2011 <notifications@github.com>
wrote:

> Hey Kevin,
>
> Can we make sure new pages are following the CSS of the rest of the site?
> for example, the "technical advisors" page under "our story" is using the
> default template, but the text appears a lot bolder/brighter than
> throughout the rest of the site. not sure why this would be...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kbauman/Capital-Sisters/issues/38>.
>



-- 
Kevin Bauman
248.935.4695
www.kevinbauman.com

**Comment by sameera2011** [comment]
hmm... i think you may be right. it may have just been the use of bold fonts, or the background image. it looked brighter for some reason. never mind. thanks for looking into it.
