### ISSUE TITLE
Form Styling

### ISSUE THREAD

**Issue by sameera2011** [kbauman/Capital-Sisters#40]
Can we adjust the styling of the pledge and donate forms to match the Contact form?

Also, currently the "donate" page is separate from the shop page. Will we need to link the two, or can we add the text from the Donate page to the Shop page? Included below for your convenience:

Unlike most non-profits, the majority of our resources are recycled rather than depleted, allowing us to leverage significant impact from a very low fixed cost base.

While our loans to microfinance institutions are funded through the sale of Sister Bonds® Investment Notes, Capital Sisters International is funded through philanthropic support from individuals and foundations and from pro bono contributions of services.

Please make a tax deductible donation to support our programs and the public launch of our Sister Bonds® Investment Fund. Be on the ground floor as we launch this exciting new venture.

Your contribution will enable us to provide zero-interest loans to our non-profit MFI partners. This is different than other investment instruments in the microfinance industry. It means that our MFIs can achieve self-sufficiency while delivering education and other critical support services to their clients through earned income.

If you would like more information about how we are funded and how your donation will support our mission, please contact us.

**Comment by kbauman** [comment]
Styled like contact and text added.
