### ISSUE TITLE
contact form

### ISSUE THREAD

**Issue by sameera2011** [kbauman/Capital-Sisters#41]
Subject drop down icon is broken

**Comment by sameera2011** [comment]
Watermark colors are appearing different in Firefox. So are asterisks

**Comment by kbauman** [comment]
This is not something that can be controlled. It is handled by the browser.
If we want asterisks to show up in most browsers they will have to be the
same color as the text.

On Tue, Mar 3, 2015 at 2:45 PM, sameera2011 <notifications@github.com>
wrote:

> Watermark colors are appearing different in Firefox. So are asterisks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kbauman/Capital-Sisters/issues/41#issuecomment-77042835>
> .
>



-- 
Kevin Bauman
248.935.4695
www.kevinbauman.com

**Comment by sameera2011** [comment]
Sorry, I wasn't very clear. The "Subject" watermark appears black while all the others appear gray. And the blue asterisks just aren't showing up at all in Firefox.

**Comment by kbauman** [comment]
The subject isn't a placeholder like the others. There isn't a way to
create placeholder text for a select. All of the text in the select has to
be the same color. If you make one light gray, it will be light gray when
something is selected as well.

For the asterisks, the only way to get them to show up on every browser is
to add them to placeholder text. The only problem there is again, you can't
change the color.

Kevin

On Wed, Mar 4, 2015 at 9:22 AM, sameera2011 <notifications@github.com>
wrote:

> Sorry, I wasn't very clear. The "Subject" watermark appears black while
> all the others appear gray. And the blue asterisks just aren't showing up
> at all in Firefox.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kbauman/Capital-Sisters/issues/41#issuecomment-77189694>
> .
>



-- 
Kevin Bauman
248.935.4695
www.kevinbauman.com

**Comment by sameera2011** [comment]
Ok. If it's easy enough, let's make it grey for the subject. or let's make all the watermarks black.

I'll go in and just input the asterisks as placeholder text for the path of least resistance. thanks!

**Comment by kbauman** [comment]
It doesn't work that way. Sorry. The placeholder text is black, it's just that browsers handle placeholder text the way they want to. We don't have exact control over it.

**Comment by sameera2011** [comment]
Ok. Well, the subject now is running up on the left line of the box. can we just adjust it so the padding is like the rest? then we'll call it good.

**Comment by sameera2011** [comment]
looks great - thank you!
