### ISSUE TITLE
Our Story page - styling is breaking when no widget is used

### ISSUE THREAD

**Issue by sameera2011** [kbauman/Capital-Sisters#42]
the text styling is not remaining consistent with the other pages when no widget is used in the sidebar. please adjust

**Comment by sameera2011** [comment]
Hey Kevin,

This doesn't look any different. The text should be brighter, like it is on other pages. See Our Story vs Resources, for example

**Comment by sameera2011** [comment]
The block quote styling is now off; it should be blue text. otherwise, looks good!

**Comment by kbauman** [comment]
Fixed.

**Comment by sameera2011** [comment]
the buttons aren't wrapping the same way they do on other landing pages

**Comment by kbauman** [comment]
That's because the content area is wider. If you want to force the buttons
to wrap, you'll need to but a <br> tag where you want the buttons to wrap.

On Fri, Mar 13, 2015 at 6:19 PM, sameera2011 <notifications@github.com>
wrote:

> Reopened #42 <https://github.com/kbauman/Capital-Sisters/issues/42>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kbauman/Capital-Sisters/issues/42#event-252863347>.
>



-- 
Kevin Bauman
248.935.4695
www.kevinbauman.com

**Comment by sameera2011** [comment]
Sorry, I meant how they're collapsing vertically when the browser screen is shrunk down. There's no vertical space between the buttons like there is on similar pages.

**Comment by kbauman** [comment]
Fixed.
