### ISSUE TITLE
Question: does the site use cookies?

### ISSUE THREAD

**Issue by sameera2011** [kbauman/Capital-Sisters#43]
They're planning on using this verbiage on the site and just need to know if it's accurate:
Capital Sisters uses cookies for a number of internal purposes related to its donors who access the website.

**Comment by kbauman** [comment]
WordPress does use cookies. They're not cookies like on other sites
however. There is no tracking, as in advetising.



On Thu, Feb 26, 2015 at 1:34 PM, sameera2011 <notifications@github.com>
wrote:

> Assigned #43 <https://github.com/kbauman/Capital-Sisters/issues/43> to
> @kbauman <https://github.com/kbauman>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kbauman/Capital-Sisters/issues/43#event-242813006>.
>



-- 
Kevin Bauman
248.935.4695
www.kevinbauman.com
