### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by sameera2011** [kbauman/Capital-Sisters#45]
Is it possible to publish future events? As of right now, it doesn't look like that's possible, as the publish date is the date that is showing for the event date.

Also, we want to hide the categories widget on the events page.

**Comment by sameera2011** [comment]
Also, on News and Events pages, when on the actual post, the "Blog" title is showing up. Can we either remove this or have it read according to the page we're on? ie. News or Events?

**Comment by kbauman** [comment]
We'll have to change the way events work in order to post future events.
Because it was requested to just use the WordPress posts functionality,
there isn't a way to schedule something in the future and have it show up
in order of scheduled date. We could add another custom field for the
actual date of the event, but then it will need to be added to every event,
or they won't all show up. It will take some time to implement.

Kevin



On Tue, Mar 3, 2015 at 2:49 PM, sameera2011 <notifications@github.com>
wrote:

> Also, on News and Events pages, when on the actual post, the "Blog" title
> is showing up. Can we either remove this or have it read according to the
> page we're on? ie. News or Events?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kbauman/Capital-Sisters/issues/45#issuecomment-77043713>
> .
>



-- 
Kevin Bauman
248.935.4695
www.kevinbauman.com

**Comment by sameera2011** [comment]
hmmm... is there a path of least resistance here? Can we make the dates being shown a separate field that is input rather than relying on the publish date? If so, this would be a field we can use across post types, whether for news, events, or blog.

**Comment by kbauman** [comment]
That's exactly what I was talking about. The date would have to be added in
ever event in a new field I create, and the read and displayed on both the
events list page and the single event page.

Kevin

**Comment by sameera2011** [comment]
Cool! Let me know if this is still feasible. And if we can get rid of the "Blog" header when looking at a full post in Events and News.

**Comment by kbauman** [comment]
It's feasible. I can add the functionality, and someone will have to go in
and add the dates.

On Fri, Mar 6, 2015 at 12:27 PM, sameera2011 <notifications@github.com>
wrote:

> Cool! Let me know if this is still feasible. And if we can get rid of the
> "Blog" header when looking at a full post in Events and News.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kbauman/Capital-Sisters/issues/45#issuecomment-77619978>
> .
>



-- 
Kevin Bauman
248.935.4695
www.kevinbauman.com

**Comment by sameera2011** [comment]
That works great! Thank you!

**Comment by sameera2011** [comment]
looking great! is it just possible to remove the categories widget from the event and news pages? then we're done here. thanks!

**Comment by sameera2011** [comment]
Reposting this from above: Also, on News and Events pages, when on the actual post, the "Blog" title is showing up. Can we either remove this or have it read according to the page we're on? ie. News or Events?
