### ISSUE TITLE
Opportunities page

### ISSUE THREAD

**Issue by sameera2011** [kbauman/Capital-Sisters#46]
Mail/share icons are not aligning properly in the right column.

Also, in IE, the contact us icon randomly reverts to just reading as "icon" instead of showing the icon itself

**Comment by kbauman** [comment]
I don't see the problem with the icons in the right column in any browser. Fixed layout issue for IE. Not seeing "icon" issue for IE.

**Comment by sameera2011** [comment]
looks good. thanks!
