### ISSUE TITLE
Invest page

### ISSUE THREAD

**Issue by sameera2011** [kbauman/Capital-Sisters#47]
Can we make the legal text on the page slightly smaller and less bold? This is the text that appears underneath the pdf forms section

**Comment by kbauman** [comment]
I made it smaller. Can't make it less bold, as it's normal weight text.

**Comment by sameera2011** [comment]
hmmm... can we adjust the color so it's not as bright then? it's brighter than the rest of the copy, it seems. then we'll call it done.

**Comment by kbauman** [comment]
The rest of the text on that page was the wrong color. See if it looks better now.

**Comment by sameera2011** [comment]
Looks awesome! Done. Thank you!!
