### ISSUE TITLE
Pledge Form

### ISSUE THREAD

**Issue by sameera2011** [kbauman/Capital-Sisters#48]
Please insert a text field next to the "other" option in investment amount. 

Please remove the line space under Investment Amount heading; 

Make it so that Investment Term only allows for one box to be checked.

Can we make the text entry boxes so that they are similarly sized to the Contact form? 

Can we make all the fields required? It's currently letting you submit without inputting name, address, etc.

I've tried to do all these things a million times and they're not working. SO frustrating.

**Comment by sameera2011** [comment]
ARGH!!!!! And i'm trying to update the text at the bottom of the form and it won't show up on the form itself; it's showing as updated in the form editor, but not on the page where the form lives.

**Comment by kbauman** [comment]
Are you updating the correct form? For some reason someone made a pledge form_copy. If you aren't updating that one, it will never change.

I did what I can, and things seem to be working. I was changing pledge form_copy, so if the other one has changes you want, you'll need to combine the two. You can see what I did in the copy. Making check boxes only have one check-able isn't possible. That's what radio button are for. I changed the check boxes to radio buttons on the copy version.

**Comment by sameera2011** [comment]
i'm a genius. that did it. thank you!

**Comment by sameera2011** [comment]
Can you adjust the styling of the Address field so the text input is in line with the rest of the form/site? Thanks!

**Comment by kbauman** [comment]
Please take a look, and see if it looks good.
