### ISSUE TITLE
text formatting - interior

### ISSUE THREAD

**Issue by sameera2011** [kbauman/Capital-Sisters#8]
please create/implement text styles that align with the designs provided. this probably just isn't done yet, but thought i'd stick it here just in case :)

**Comment by sameera2011** [comment]
hey guys - wanted to follow up on this as well. in addition to needing the short codes and wysiwig styles input, we also need the headings/subheadings/featured content to more closely align to the designs. Jenny will be sending you a document detailing this.

**Comment by michaellaness** [comment]
remaining styles that need to be fixed:
- [ ] turquoise subheadlines
- [ ] interior slider - spacing & headline styles
- [ ] landing page intro sections
- [ ] contact section: dropdown arrow, add required field labels, button pointer state
- [ ] team page - spacing on social icons
- [ ] style 'more >' link

**Comment by michaellaness** [comment]
All styles and shortcodes are done now, here is a sample page for you guys to reference: http://csi:8888/placeholder-headline/

If I've left anything out or there are still some tweaks needed, add a comment with a description of what it is and a screenshot.

**Comment by sameera2011** [comment]
bold and italic styles are not showing up

**Comment by michaellaness** [comment]
bold and italic styles should work now

**Comment by sameera2011** [comment]
the bullet points are not working and are instead shrinking the text as seen in attached screen grab
![screen shot 2015-01-15 at 10 09 02 am](https://cloud.githubusercontent.com/assets/10201361/5762339/af6e201e-9c9e-11e4-911b-b0cd94a6c910.png)

**Comment by sameera2011** [comment]
just wanted to follow up on this - the bullet points are not formatting properly.

**Comment by kbauman** [comment]
Should be good now.
